### ISSUE TITLE
Hotkey for processing pipeline

### ISSUE THREAD

**Issue by Rapdrei** [05dirnbe/nefi#21]
shift + enter run hotkey

**Comment by LumPenPacK** [comment]
Added with c7123eb
But shortcut button is "F1" for now since Qt didn't recognize "Shift + Enter" as a hotkey. If it's important to have these keys explicitly I can look into it again.

**Comment by 05dirnbe** [comment]
I dislike F1 as the run hotkey. Id rather have something more central on the keyboard. ctrl + space for exampel. shift+enter is still my favourite though.

**Comment by tastyminerals** [comment]
The hotkey for running the pipeline was **ctrl + r**, I remember adding it.

**Comment by tastyminerals** [comment]
**ctrl + space** is problematic because it is frequently used for language layout switching.

**Comment by LumPenPacK** [comment]
You're right. We already added it at a different position. I'm going to change it to "shift + enter" though. I just need to take a look into QT documentation again since menu shortcuts work a little bit different than the shortcuts we used before. We should use menu shortcuts because they can be seen for every user in the menu bar.

**Comment by LumPenPacK** [comment]
Added with 9c382da
