### ISSUE TITLE
Let pipeline draw Skeleton image

### ISSUE THREAD

**Issue by Rapdrei** [05dirnbe/nefi#30]
Our pipeline does not print the skeleton in the guo and hall graph detection.

**Comment by LumPenPacK** [comment]
And we need to think about how we can add this with the current implementation of the pipeline. For now every step can only provide one picture/graph but for the skeleton the Guo-Hall algorithm basically need to export two pictures.

There might be two possible workaround for this.

1. Add a new Algorithm called "Guo-Hall Skeleton" which can only be applied after "Guo-Hall". We can just add a new rule to our "Sanity Check" so this Algorithm can only be applied on this position.

2. Modify pipeline in order to allow more than one object can be returned for one step. Instead of returning just one image/graph for each step we should return an array of objects. This is the the better solution in my opinion but there might be a lot of changes necessary to provide that.

**Comment by Rapdrei** [comment]
Actually i dont like the idea of seperating the steps. I think we could adjust the pipeline to take a list of images in results['image'] and draw all of them.
