### ISSUE TITLE
"mathematical" output

### ISSUE THREAD

**Issue by buhl22** [05dirnbe/nefi#41]
Hello,
I have a qeustion concerning the output file which gives us the description of the graph.
Like this: (272, 78)|{'pixels': 19, 'width': 16.263157894736842, 'width_var': 83.036011080332415, 'length': 25.970568}
I haven't found an explanation of the different components in the documentation, but maybe I just did not look properly.
Is there an explanation somewhere? Or could you give a short one.

Kind regards Benjamin

**Comment by Rapdrei** [comment]
Hello Benjamin,
we are using networkx for NEFI please refer to their documentation https://networkx.github.io/ .
Aside of what we already have, we save some variables like width, length, pixels and width variance in order to draw our graph lines in the original image correctly. 
The first tuple refers to the edge between node 272 and 78.
Best,
Dennis

**Comment by buhl22** [comment]
Thank you!
