### ISSUE TITLE
A trouble during the installation process 

### ISSUE THREAD

**Issue by azzouztr** [05dirnbe/nefi#42]
I tried to install NEFI.exe but it seems that there's a problem. There is a message that appears each time during the installation process "NEFI.exe has stopped working" 

Is there please anybody have a solution for this problem

**Comment by LumPenPacK** [comment]
Have you extracted the whole folder on your disk?
Please start the nefi_debug.exe to get some more information what has caused the crash.

**Comment by azzouztr** [comment]
Yes, I have extracted the whole folder on my disk
When I tried to run nefi_debug.exe, I have obtained this message error " ImportError: DLL load failed with error code -1073731795 "

**Comment by LumPenPacK** [comment]
What OS are you running? The precompiled package only supports 64Bit Windows for now.

**Comment by Rapdrei** [comment]
Hi azzouztr,

> Yes, I have extracted the whole folder on my disk
When I tried to run nefi_debug.exe, I have obtained this message error " ImportError: DLL load failed with error code -1073731795 "

That really sounds to me as your extraction failed and you miss one of the resources. Could you please try to download and extract the software again?
Also please leave use more details about your system:
- Which windows Version you are using?
- 32 or 64 bits?
Best

**Comment by azzouztr** [comment]
Currently, I use windows 64 bits. I'll try again and I'll keep you informed.
Thank you for your help.

**Comment by LumPenPacK** [comment]
Which iteration of Windows exactly? Windows 7, 8, 10?

**Comment by azzouztr** [comment]
I use windows 7 64 bits

**Comment by Rapdrei** [comment]
fresh download & extraction didn't solve the problem?

> I use windows 7 64 bits 

It should work on your machine as you match the requirements.
I also assume that you really downloaded the Windows version?!

If neither solves your problem, we need to setup a vm with win7 64 and try to reproduce the error. Can you also try to disable all services currently instantiated. This should not make a difference but worth to give it a try.

**Comment by azzouztr** [comment]
Hi again, 
I already use windows 7 64 bits. Is there another specific requirements that I should satisfy them before running run nefi_debug.exe ?

**Comment by LumPenPacK** [comment]
Usually it should already work out of the box but I'm not sure whether we've ever tried the precompiled package on Windows 7 though. 
Does the debug console give you any additional output? For now I don't really have any clue what could cause this error. There might be some dynamic linked libraries missing for Windows 7 or some of the static libraries we use in this package could be not compatible with Windows 7 but that's just some guessing. I'm going to try this with Windows 7 and give you some feedback.

**Comment by azzouztr** [comment]
@LumPenPacK  Do you have any news about my problem ?

**Comment by LumPenPacK** [comment]
Yes. I could try this on a machine with Windows 7 and I got the same error message. It seems to be a problem with the opencv module. I'll try to compile this module with Windows 7 which might solve the problem but I need to set up a Windows 7 VM first.

**Comment by azzouztr** [comment]
@LumPenPacK  keep me informed please

**Comment by LumPenPacK** [comment]
Yesterday I was able to get the same error message you got on an old Windows 7 machine which has not been used for months/years.
Now I tried it again on a fresh installation of Windows 7 64bit and I was able to start Nefi.exe without any problems after I'd installed all the available upgrades for Windows 7.
There is probably a Windows upgrade which has updated some libraries we used for compiling and which are mandatory to run some of the libraries NEFI needs. That's why I recommend you to install all available Windows updates and try it again.

**Comment by azzouztr** [comment]
@LumPenPacK 

I have installed all the updates but the problem didn't resolved yet. What should I do in this case ?

**Comment by Astarin** [comment]
@azzouztr @LumPenPacK 

Hello, I just wanted to install NEFI and it seems I have the same issue as azzouztr. When I click on NEFI.exe to install it, nothing happens and than the message "NEFI.exe has stopped working" appears. I have got Win 7 64 bit as well. 

These are information about the problem:
"Files, which describe the problem:
  C:\Users\Michal\AppData\Local\Temp\WERDE60.tmp.WERInternalMetadata.xml
  C:\Users\Michal\AppData\Local\Temp\WERE4F6.tmp.appcompat.txt
  C:\Users\Michal\AppData\Local\Temp\WERE584.tmp.hdmp "

Have you solved it anyhow yet?

**Comment by 05dirnbe** [comment]
Hello guys, please excuse this late reply. It is unfortunate that Astarin and azzouztr cant run NEFI. Given the fact that we are still able to install and use NEFI on our windows test systems, it seems likely that the issue is not on our end. Since we cannot reproduce these issues, our hands are effectively tied. 

However, please remember that you can still run NEFI on **Windows from source** after installing python and the required libraries, see [dependencies](http://nefi.mpi-inf.mpg.de/documentation/rst_files/Technologies.html). Compared to the pre-compiled binaries, this approach is much less likely to fail on your systems and in case of errors, they are probably more telling.

I recommend the two of you to download the newest NEFI source code from the repo and run it directly on Windows. This is what works fine on Linux and Mac and provided the dependencies are covered, there is no reason to believe it will fail on Windows as far as I can tell. Alternatively, if you have the possibility, you might try to move to Linux or Mac and run NEFI there. For instance, I run NEFI on Mac primarily but Ive successfully used it from a USB stick Linux installation in the past.

Should you encounter problems while trying any of the above suggestions. Do not hesitate to open a new issue/question and the guys will try to help you out.
